version: '3'

services:
  db:
    build: .
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - ./app:/app
    restart: always
